### ISSUE TITLE
openvscode docker container support for Cody extension auth signin deadend

### ISSUE THREAD

**Issue by maestrocoder** [sourcegraph/cody#2066]
### Discussed in https://github.com/sourcegraph/cody/discussions/2065

<div type='discussions-op-text'>

<sup>Originally posted by **maestrocoder** December  2, 2023</sup>
hello, using Cody extension in vscode desktop on PC/MAC just fine! Great product!! moving work to private linux server using openvscode docker containers for CDE.  

Cody won't login using openvscode?  can someone guide me on how to fix this or what work-around solutions?  the extension will install into openvscode but it will not signin.  Cody requires some auth, it appears the openvscode port needs a patch?

here an example docker-compose.yml

```
version: "2.1"
services:
  openvscode-server:
    image: lscr.io/linuxserver/openvscode-server:latest
    container_name: project1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CONNECTION_TOKEN=
      - CONNECTION_SECRET=
      - SUDO_PASSWORD=password
      - SUDO_PASSWORD_HASH=
    volumes:
      - /home/user/workspaces/project1/config:/config
    ports:
      - 3000:3000
    restart: unless-stopped
```

so just docker compose up 
```
docker-compose up -d
```

and after it's running open http://yourip:3000

then install Cody extension but it won't sign in.  

Is this patchable or could there be a limitation from the desktop port to openvscode?  

Any guidance appreciated in advance or if we just need some configuration work-around for the docker containers running the openvscode.
