### ISSUE TITLE
feedback: support for custom openai endpoint

### ISSUE THREAD

**Issue by sozercan** [sourcegraph/cody#3000]
### Version

v1.3.1706800162

### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [x] Other

### What needs to be improved? Please describe how this affects the user experience.

Support for user specified custom openai-compatible endpoint (similar to ollama endpoint)

This will also help with Azure OpenAI integration

### Describe the solution you'd like to see

cody working with openai api compatible open-source llm inference engines such as https://github.com/mudler/LocalAI and https://github.com/sozercan/aikit

**Comment by jdorfman** [comment]
Thanks @sozercan will let the team know!

**Comment by kqvanity** [comment]
@jdorfman
Hello. I've been trying to chat with cody with another OpenAI-compatible client (aichat) after I came across [this](https://sourcegraph.com/docs/CHANGELOG#cody-1) which mention `For compatibility with OpenAI clients, it's possible to use Bearer TOKEN header with all API endpoints that start with the prefix /.api/llm.`. However, it doesn't seem to work!
that's my current setup
```
 - type: openai-compatible
    name: cody
    api_base: https://sourcegraph.com/.api/llm
    api_key: ...
    models:
      anthropic/claude-3-sonnet-20240229
      max_input_tokens: 131072
```
